name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build KG Parser
    runs-on: ubuntu-latest
    # for local run --  $ act -j build -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
         # for act caching download https://static.azul.com/zulu/bin/zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz
         # to root workdir an uncomment
         # jdkFile: zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clone kefir
        uses: actions/checkout@v2
        with:
          repository: dmitry-weirdo/pda-kefir
          path: kefir
          # for local act  
          # token:   

      - name: Install kefir
        working-directory: kefir
        run: |
          mvn install -DskipTests -Dmaven.javadoc.skip --no-transfer-progress
          rm -rf kefir

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with: 
          languages: java
          queries: security-and-quality

      # - name: Build kgparser project
      #   run: mvn package -Dmaven.javadoc.skip --no-transfer-progress

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -Dmaven.javadoc.skip --no-transfer-progress sonar:sonar -Dsonar.projectKey=kghackers_kgparser -Dsonar.organization=kghackers -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=src/main

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TGBOT_CHAT }}
          token: ${{ secrets.TGBOT_TOKEN }}
          status: ${{ job.status }}